services:

  postgres:
    image: postgres:17
    container_name: retailpulse-postgres

    environment:
      POSTGRES_USER: retailpulse
      POSTGRES_PASSWORD: retailpulse
      POSTGRES_DB: retailpulse

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U retailpulse -d retailpulse"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: